"""End-to-end ASR tests against real synthesised speech.

Fixtures are generated by Windows SAPI (see tests/fixtures/README.md), so there
is a known ground truth to assert against without anyone having to speak into a
microphone.

These need the models and a GPU, so they are marked ``slow`` and skipped when
the models are absent:

    pytest -m slow
"""

from __future__ import annotations

import wave
from pathlib import Path

import pytest

from lwstt.core.chunker import Action, decide
from lwstt.core.textproc import normalize_newlines

FIXTURES = Path(__file__).parent / "fixtures"
MODEL_DIR = Path(r"%USERPROFILE%\ai-models")
LARGE = MODEL_DIR / "faster-whisper-large-v3"
TURBO = MODEL_DIR / "faster-whisper-large-v3-turbo"

pytestmark = [
    pytest.mark.slow,
    pytest.mark.skipif(not LARGE.is_dir(), reason="large-v3 model not installed"),
]


def load_wav(path: Path):
    from lwstt.worker import asr

    with wave.open(str(path), "rb") as handle:
        frames = handle.readframes(handle.getnframes())
        duration = handle.getnframes() / handle.getframerate()
    return asr.pcm_to_float(frames), duration


@pytest.fixture(scope="module")
def final_slot():
    from lwstt.worker import asr

    return asr.ModelSlot(str(LARGE), "cuda", "float16")


@pytest.fixture(scope="module")
def preview_slot():
    from lwstt.worker import asr

    return asr.ModelSlot(str(TURBO), "cuda", "float16")


def normalise(text: str) -> str:
    return normalize_newlines(text).lower().strip(" .")


class TestTranscription:
    def test_simple_sentence(self, final_slot):
        from lwstt.worker import asr

        audio, _ = load_wav(FIXTURES / "simple.wav")
        text = asr.segments_text(asr.transcribe(final_slot, audio, beam_size=5))
        assert normalise(text) == "the quick brown fox jumps over the lazy dog"

    def test_two_sentences(self, final_slot):
        from lwstt.worker import asr

        audio, _ = load_wav(FIXTURES / "two_part.wav")
        text = normalise(asr.segments_text(asr.transcribe(final_slot, audio, beam_size=5)))
        assert "first sentence here" in text
        assert "second sentence follows" in text

    def test_turbo_agrees_with_large(self, preview_slot, final_slot):
        """The preview model should not be saying something different."""
        from lwstt.worker import asr

        audio, _ = load_wav(FIXTURES / "simple.wav")
        turbo = normalise(asr.segments_text(asr.transcribe(preview_slot, audio, beam_size=1)))
        large = normalise(asr.segments_text(asr.transcribe(final_slot, audio, beam_size=5)))
        assert turbo == large

    def test_numbers_are_left_as_whisper_renders_them(self, final_slot):
        """Decided in PLAN.md: no normalisation. This pins the actual behaviour."""
        from lwstt.worker import asr

        audio, _ = load_wav(FIXTURES / "numbers.wav")
        text = normalise(asr.segments_text(asr.transcribe(final_slot, audio, beam_size=5)))
        assert "widgets by friday afternoon" in text
        assert "25" in text or "twenty five" in text


class TestSilenceGuard:
    """The failure mode this guard exists for, verified against the real model."""

    def test_vad_finds_no_speech_in_silence(self):
        import numpy as np

        from lwstt.worker import asr

        assert asr.speech_segments(np.zeros(16000 * 3, dtype="float32")) == []

    def test_silence_reaches_the_model_only_as_a_hallucination(self, final_slot):
        """Documents *why* the guard exists: without it, silence becomes text."""
        import numpy as np

        from lwstt.worker import asr

        silence = np.zeros(16000 * 3, dtype="float32")
        leaked = asr.segments_text(asr.transcribe(final_slot, silence, vad_filter=False))
        assert leaked != "", "expected Whisper to hallucinate on pure silence"

    def test_chunker_drops_silence_before_it_reaches_the_model(self):
        import numpy as np

        from lwstt.worker import asr

        silence = np.zeros(16000 * 3, dtype="float32")
        speech = asr.speech_segments(silence)
        result = decide(speech, 3.0, 0.8, 25.0, ended=True)
        assert result.action is Action.DROP
        assert not result.should_transcribe


class TestChunkBoundaries:
    def test_internal_gap_is_found(self):
        from lwstt.worker import asr

        audio, _ = load_wav(FIXTURES / "two_part.wav")
        speech = asr.speech_segments(audio)
        assert len(speech) == 2, "the 1.5 s break should split into two regions"
        gap = speech[1].start - speech[0].end
        assert gap > 0.8, f"gap of {gap:.2f}s should exceed the default threshold"

    def test_streaming_closes_the_chunk_during_the_gap(self):
        """Simulates the real loop: decide() is called as audio accumulates."""
        from lwstt.worker import asr

        audio, duration = load_wav(FIXTURES / "two_part.wav")
        rate = 16000
        closed_at = None
        step = 0.1
        elapsed = step
        while elapsed <= duration:
            window = audio[: int(elapsed * rate)]
            speech = asr.speech_segments(window)
            result = decide(speech, elapsed, 0.8, 25.0, ended=False)
            if result.action is Action.CLOSE:
                closed_at = result.cut_at
                break
            elapsed += step
        assert closed_at is not None, "should close during the pause"
        assert 1.0 < closed_at < 3.0, f"cut at {closed_at:.2f}s is not in the gap"

    def test_release_closes_and_trims_trailing_silence(self):
        from lwstt.worker import asr

        audio, duration = load_wav(FIXTURES / "simple.wav")
        speech = asr.speech_segments(audio)
        result = decide(speech, duration, 0.8, 25.0, ended=True)
        assert result.action is Action.CLOSE
        assert result.cut_at < duration, "trailing silence must be trimmed off"


class TestModelSlot:
    def test_lazy_load_and_unload(self):
        from lwstt.worker import asr

        slot = asr.ModelSlot(str(TURBO), "cuda", "float16")
        assert not slot.loaded
        slot.get()
        assert slot.loaded
        assert slot.load_seconds > 0
        slot.unload()
        assert not slot.loaded

    def test_real_tokenizer_counts_the_vocabulary_budget(self, final_slot):
        from lwstt.core.wordlists import fit_to_budget
        from lwstt.worker import asr

        counter = asr.count_tokens_with(final_slot)
        assert counter("Hopf") >= 1
        terms = [f"term{i}" for i in range(500)]
        kept = fit_to_budget(terms, 224, counter)
        assert 0 < len(kept) < len(terms)
